### ISSUE TITLE
Add badges for readme using npm-badger

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/exgen#20]
1. Install npm badger `npm install npm-badger -g`
2. Clone this repository `git clone https://github.com/arshadkazmi42/exgen`
3. Go to root directory `cd exgen`
4. Run npm badger `npm-badger`
5. Commit `README.md` file
6. Create Pull Request

**Comment by shikhar13012001** [comment]
I would like to work on this issue @arshadkazmi42

**Comment by arshadkazmi42** [comment]
@shikhar13012001 Sure. go ahead

**Comment by arshadkazmi42** [comment]
@shikhar13012001 Any updates on this?

**Comment by shikhar13012001** [comment]
I have created a pull request #21 please review my PR and let me know if you need any further changes.

**Comment by arshadkazmi42** [comment]
Ah. right. I think I missed it before. Merged
