### ISSUE TITLE
remove yarn.lock file

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/exgen#8]
- Delete yarn.lock
- Delete package-lock.json
- Run npm install
- Commit all the changes 
- Create a Pull request

**Comment by learningmode** [comment]
Hi,
I would like to work on this

**Comment by arshadkazmi42** [comment]
@learningmode go ahead

**Comment by learningmode** [comment]
I created the pull request

**Comment by ShubhankerS** [comment]
Hi
I am a beginner and I would like to work on this.

**Comment by arshadkazmi42** [comment]
@ShubhankerS this has already been fixed and merged.

**Comment by arshadkazmi42** [comment]
@ShubhankerS you could take this, this is similar https://github.com/gh-conf/rhof/issues/35
